name: melodistic
description: Music mood classification for a workout program

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  dio: ^4.0.6
  just_audio: ^0.9.25
  google_sign_in: ^5.3.3
  flutter_spinkit: ^5.1.0
  get: ^4.6.5
  image_picker: ^0.8.6
  syncfusion_flutter_sliders: ^20.2.49
  shared_preferences: ^2.0.15
  http_parser: ^4.0.1
  file_picker: ^5.2.1
  dotted_border: ^2.0.0+2

dev_dependencies:
  flutter_lints: ^1.0.0
  any_link_preview: ^2.0.9
  flutter_launcher_icons: ^0.10.0
  
dependency_overrides:
  image_picker_ios:
    git:
      url: https://github.com/ggolfz/image_picker_ios
      ref: main

flutter_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/logo/Logo.png"
  min_sdk_android: 21

flutter:
  uses-material-design: true
  assets:
    - assets/images/   
  fonts:
    - family: Poppins
      fonts:
        - asset: assets/fonts/Poppins-Regular.ttf
        - asset: assets/fonts/Poppins-Medium.ttf
          weight: 500
        - asset: assets/fonts/Poppins-SemiBold.ttf
          weight: 600
        - asset: assets/fonts/Poppins-Bold.ttf
          weight: 700
    - family: MelodisticIcon
      fonts:
        - asset: assets/icons/Icon.ttf
        
