# This workflow uses actions that are not certified by GitHub.
# They are provided by a third-party and are governed by
# separate terms of service, privacy policy, and support
# documentation.

name: Format and Test

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main", "develop" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      
      - name: Install Flutter
        uses: britannio/action-install-flutter@v1.1
      
      - name: Install Flutter Dependencies
        run: flutter pub get
        
      - name: Verify formatting
        run: .ci/check-format.sh

      - name: Analyze project source
        run: flutter analyze
